Resources:
 NewVolume:
  Type: AWS::EC2::Volume
  Properties: 
    Size: 100
    Encrypted: ""
    AvailabilityZone: !GetAtt Ec2Instance.AvailabilityZone
    Tags:
      - Key: MyTag
        Value: TagValue
  DeletionPolicy: Snapshot
