AWSTemplateFormatVersion: '2010-09-09'
Description: Set Lifecycle Configuration
Resources:
  S3Bucket:
  Properties:
    BucketName: cc-prod-web-data
    AccessControl: Private
    LifecycleConfiguration:
      Rules:
      - Id: cc-transition-access-log-data
        Prefix: log
        Status: Enabled
        ExpirationInDays: 365
        Transitions:
        - TransitionInDays: 30
          StorageClass: STANDARD_IA
        - TransitionInDays: 60
          StorageClass: GLACIER
  Type: AWS::S3::Bucket
